  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
 23
 24
 25
 26
 27
 28
 29
 30
 31
 32
 33
 34
 35
 36
 37
 38
 39
 40
 41
version: "3.8"
services:
  lotto-prediction:
    build: ./projects/lotto-prediction
    container_name: lotto-prediction
    tty: true
    ports:
      - "8501:8501"
    restart: unless-stopped

  LotteryAi:
    build: ./projects/LotteryAi
    container_name: LotteryAi
    tty: true
    ports:
      - "8502:8501"
    restart: unless-stopped

  LotteryPredict:
    build: ./projects/LotteryPredict
    container_name: LotteryPredict
    tty: true
    ports:
      - "8503:8501"
    restart: unless-stopped

  lottokit:
    build: ./projects/lottokit
    container_name: lottokit
    tty: true
    ports:
      - "8504:8501"
    restart: unless-stopped

  topic-search:
    build: ./projects/topic-search
    container_name: topic-search
    tty: true
    ports:
      - "8505:8501"
    restart: unless-stopped